//
//  SurveyModel+Other.h
//  VinoCharts
//
//  Created by Ang Civics on 29/3/13.
//  Copyright (c) 2013 nus.cs3217. All rights reserved.
//
/*
 Additional method to support core data autogenerated SurveyModel class
 */

#import "SurveyModel.h"
#import "CoreDataConstant.h"
#import "Survey.h"

@interface SurveyModel (Other)

-(id)copySurveyData:(SurveyModel *)survey;
//REQUIRES: self is created in the correct context and the survey is not nil
//EFFECTS: copy all survey data to replace self data

-(void)retrieveSurveyData:(Survey*)survey;
//REQUIRES: self is created in the correct context and the survey is not nil
//EFFECTS: translate survey class data to match core data saving type then modify self property

@end
